debug: False
seed: 31299
checkpoints_dir: checkpoints/
device: cuda
num_workers: 4
batch_expansion_th: 0.7
modalities: [image_stereo_centre, image_mono_rear, image_mono_left, image_mono_right,]
test_modality: image
epochs: 60
