_target_: opr.models.base_models.ComposedModel

image_module: null
cloud_module: null
fusion_module: null
 
text_module:
  _target_: opr.models.base_models.FusionTextModel
  pca_size: 100
  hidden_size: 100
