_target_: opr.models.base_models.ComposedModel

chonky_module:
  _target_: opr.models.base_models.DoubleImageModule

  backbone:
    _target_: opr.models.resnet.ChonkyNet
    lateral_dim: 128
    fh_num_bottom_up: 4
    fh_num_top_down: 0
    pretrained: True

  head:
    _target_: opr.models.layers.gem.DoubleGeM
    p: 3
    eps: 0.000001

fusion_module:
  _target_: opr.models.fusion.Concat
