_target_: opr.models.base_models.ComposedModel

cloud_module:
  _target_: opr.models.base_models.CloudModule

  backbone:
    _target_: opr.models.minkloc.MinkResNetFPNExtractor
    out_channels: 256
    num_top_down: 2
    conv0_kernel_size: 5
    block: ECABasicBlock
    layers: [1, 1, 1, 1]
    planes: [64, 128, 64, 32]

  head:
    _target_: opr.models.layers.gem.MinkGeM
    p: 3
    eps: 0.000001
