_target_: opr.datasets.itlp.ITLPCampus
defaults:
 - _self_
 - sensors_cfg: husky
 - anno: ade20k


dataset_root: /home/docker_opr/Datasets/indoor/
csv_file: "dataset.csv"
sensors: []
load_semantics: False
load_soc: True
top_k_soc: 10
max_distance_soc: 50.0
indoor: True
train_split: [1, 3, 5] # floors
test_split: [2, 4] # floors