_target_: opr.datasets.nclt.NCLTDataset

dataset_root: ???
subset: train
data_to_load: [pointcloud_lidar]
positive_threshold: 10.0
negative_threshold: 50.0
pointcloud_quantization_size: 0.5
max_point_distance: null
spherical_coords: False
