_target_: opr.datasets.nclt.NCLTDataset
defaults:
 - _self_
 - anno: oneformer

dataset_root: ???
data_to_load: [pointcloud_lidar,]
positive_threshold: 10.0
negative_threshold: 50.0
images_dirname: images_small
masks_dirname: segmentation_masks_small
pointclouds_dirname: velodyne_data
use_minkowski: False
pointcloud_quantization_size: 0.5
max_point_distance: 100.0
normalize_point_cloud: False
num_points_sample: 8192
spherical_coords: False
use_intensity_values: False
image_transform: null
semantic_transform: null
pointcloud_transform: null
pointcloud_set_transform: null

load_soc: False
top_k_soc: 5
max_distance_soc: 50.0
