dataset:
  _target_: opr.datasets.oxford.OxfordDataset

  dataset_root: /home/docker_opr/Datasets/pnvlad_oxford_robotcar
  modalities: [image, cloud,]
  images_subdir: stereo_centre_small
  random_select_nearest_images: False
  mink_quantization_size: 0.01

sampler:
  _target_: opr.datasets.samplers.batch_sampler.BatchSampler

  batch_size: 8
  batch_size_limit: 160
  batch_expansion_rate: 1.4
  positives_per_group: 2
  seed: 3121999

num_workers: 4
