dataset:
  _target_: opr.datasets.oxford.OxfordDataset

  dataset_root: /home/docker_opr/Datasets/pnvlad_oxford_robotcar
  modalities: ${general.modalities}
  images_subdir: stereo_centre_small
  random_select_nearest_images: False
  mink_quantization_size: 0.01

sampler:
  _target_: opr.datasets.samplers.batch_sampler.BatchSampler

  batch_size: 8
  batch_size_limit: 128
  batch_expansion_rate: 1.4
  positives_per_group: 2
  seed: ${general.seed}

num_workers: ${general.num_workers}
