_target_: opr.models.place_recognition.soc.SOCMLPMixer

num_classes: ${dataset.anno.num_special} # 72 for ade20k
num_objects: ${dataset.top_k_soc}
embeddings_size: 256
patch_size: 1 # should be divider of num_classes
hidden_dim: 64
depth: 3