defaults:
  - _self_
  - model: minkloc_multimodal
  # - model: text_model
  # - dataset: nclt
  - dataset: itlp_campus
  # - loss: triplet_margin
  - optimizer: adam
  - scheduler: multi_step

loss: 
  _target_: opr.losses.MultimodalTripletMarginLoss
  margin: 0.2
  swap: True
  distance:
    _target_: pytorch_metric_learning.distances.LpDistance
    normalize_embeddings: False
    collect_stats: True
  miner:
    _target_: opr.miners.HardTripletMiner
    distance:
      _target_: pytorch_metric_learning.distances.LpDistance
      normalize_embeddings: False
    modalities: ${loss.modalities}
  reducer:
    _target_: pytorch_metric_learning.reducers.AvgNonZeroReducer
    collect_stats: True
  modalities: [image, cloud]
  weights: [0.5, 0.5]

general:
  debug: False
  seed: 31299
  checkpoints_dir: checkpoints/
  device: cuda
  num_workers: 4
  batch_expansion_th: 0.7
  modalities: [image, cloud]
  epochs: 40


wandb:
  disabled: False
  project: OpenPlaceRecognition
  run_name: lidar+camera
