## image+semantic config
defaults:
  - _self_
  - model: minkloc_multimodal_is # default: minkloc_multimodal
  - dataset: nclt_semantic # default: nclt
  - loss: triplet_margin_is
  - optimizer: adam
  - scheduler: multi_step

general:
  debug: False
  seed: 31299
  checkpoints_dir: checkpoints/
  device: cuda
  num_workers: 4
  batch_expansion_th: 0.7
  modalities: [image, semantic] # default: [image, cloud]
  test_modality: fusion
  epochs: 30 # default: 2

wandb:
  disabled: False
  project: OpenPlaceRecognition
  run_name: null
