defaults:
  - _self_
  # - model: nclt_multitext_model
  - dataset: nclt_text
  - optimizer: adam
  - scheduler: multi_step

general:
  debug: False
  seed: 31299
  checkpoints_dir: checkpoints/
  device: cuda
  num_workers: 4
  batch_expansion_th: 0.7
  modalities: [text_cam5, text_cam2, text_cam1, text_cam3, text_cam4]
  test_modality: text
  epochs: 60

model:
  _target_: opr.models.base_models.ComposedModel
  image_module: null
  cloud_module: null
  fusion_module: null
  text_module:
    _target_: opr.models.base_models.MultiTextModule
    text_module: 
      _target_: opr.models.base_models.TextModule
      text_emb_size: 100
      hidden_size: 100
    fusion_module:
      _target_: opr.models.fusion.Add


loss: 
  _target_: opr.losses.MultimodalTripletMarginLoss
  margin: 0.2
  swap: True
  distance:
    _target_: pytorch_metric_learning.distances.LpDistance
    normalize_embeddings: False
    collect_stats: True
  miner:
    _target_: opr.miners.HardTripletMiner
    distance:
      _target_: pytorch_metric_learning.distances.LpDistance
      normalize_embeddings: False
    modalities: ${loss.modalities}
  reducer:
    _target_: pytorch_metric_learning.reducers.AvgNonZeroReducer
    collect_stats: True
  modalities: [text]
  weights: [1]


wandb:
  disabled: False
  project: OpenPlaceRecognition
  run_name: only_text_PCA_all_cam_Add
