defaults:
  - _self_
  - model: minkloc_multimodal
  - dataset: oxford
  - loss: triplet_margin
  - optimizer: adam
  - scheduler: multi_step
  - general: multimodal

wandb:
  disabled: False
  project: OpenPlaceRecognition
  run_name: null
