defaults:
  - _self_
  - model: minkloc_multimodal
  - dataset: phystech_campus
  - loss: triplet_margin
  - optimizer: adam
  - scheduler: multi_step

general:
  checkopoints_dir: checkpoints/
  device: cuda
  batch_expansion_th: 0.7
  modalities: [image, cloud,]
  epochs: 60
