defaults:
  - _self_
  - model: minkloc_multimodal
  - dataset: oxford
  - loss: triplet_margin
  - optimizer: adam
  - scheduler: multi_step

general:
  debug: False
  seed: 31299
  checkpoints_dir: checkpoints/
  device: cuda
  num_workers: 4
  batch_expansion_th: 0.7
  modalities: [image, cloud,]
  test_modality: fusion
  epochs: 60

wandb:
  disabled: False
  project: OpenPlaceRecognition
  run_name: null
