defaults:
  - _self_
  - dataset: nclt
  - sampler: batch_sampler
  - model: place_recognition/resnet18_gem
  - loss: batch_hard_triplet_margin
  - optimizer: adamw
  - scheduler: multi_step

wandb:
  disabled: false
  project: SeqPlaceRecognition

debug: false
device: cuda
seed: 3121999
num_workers: 4

exp_name: ???

epochs: 80
batch_expansion_threshold: 0.7
