# Configuration for OCR model
# prediction_engine:
use_gpu: true
use_xpu: false
use_npu: false
ir_optim: true
use_tensorrt: false
min_subgraph_size: 15
precision: "fp32"
gpu_mem: 500
gpu_id: 0

# text_detector:
image_dir: null
page_num: 0
det_algorithm: "DB"
det_model_dir: "./../../weights/paddleocr/infer/det_db_inference_v2/"
det_limit_side_len: 960.0
det_limit_type: "max"
det_box_type: "quad"

# det_db_params:
det_db_thresh: 0.3
det_db_box_thresh: 0.6
det_db_unclip_ratio: 1.5
max_batch_size: 10
use_dilation: false
det_db_score_mode: "fast"

# det_east_params:
det_east_score_thresh: 0.8
det_east_cover_thresh: 0.1
det_east_nms_thresh: 0.2

# det_sast_params:
det_sast_score_thresh: 0.5
det_sast_nms_thresh: 0.2

# det_pse_params:
det_pse_thresh: 0
det_pse_box_thresh: 0.85
det_pse_min_area: 16
det_pse_scale: 1

# fce_params:
scales: [8, 16, 32]
alpha: 1.0
beta: 1.0
fourier_degree: 5

# text_recognizer:
rec_algorithm: "STARNet"
rec_model_dir: "./../../weights/paddleocr/infer/infer_mv3_v2/"
rec_image_inverse: true
rec_image_shape: "3, 48, 320"
rec_batch_num: 6
max_text_length: 25
rec_char_dict_path: "./../../weights/paddleocr/ru_dict_2.txt"
use_space_char: true
vis_font_path: "./doc/fonts/simfang.ttf"
drop_score: 0.5

# e2e_params:
e2e_algorithm: "PGNet"
e2e_model_dir: null
e2e_limit_side_len: 768.0
e2e_limit_type: "max"
e2e_pgnet_score_thresh: 0.5
e2e_char_dict_path: "./ppocr/utils/ic15_dict.txt"
e2e_pgnet_valid_set: "totaltext"
e2e_pgnet_mode: "fast"

# text_classifier:
use_angle_cls: false
cls_model_dir: null
cls_image_shape: "3, 48, 192"
label_list: ['0', '180']
cls_batch_num: 6
cls_thresh: 0.9

# optimization:
enable_mkldnn: false
cpu_threads: 10
use_pdserving: false
warmup: false

# sr_params:
sr_model_dir: null
sr_image_shape: "3, 32, 128"
sr_batch_num: 1

# output:
draw_img_save_dir: "./inference_results"
save_crop_res: false
crop_res_save_dir: "./output"

# multi_process:
use_mp: false
total_process_num: 1
process_id: 0

# benchmark:
benchmark: false
save_log_path: "./log_output/"

# logging:
show_log: true
use_onnx: false
